.TH soundinfo 1 "27 Oct 1996" "Release 1" "Linux System Manual"
.SH NAME
soundinfo \- Describes parts of the Linux Sound system support
.SH SYNOPSIS
.B soundinfo
[options]
.SH DESCRIPTION
.I soundinfo
, describes parts of the Linux Sound system support in the current kernel.
Output is to stdout and you may wish to pipe the output thru' your favorite
pager.
.PP
Currently only the capabilities and features of /dev/mixer and /dev/dsp
are displayed. If your devices have different names (e.g. you have more than
one sound card - or you are just plain perverse :-) then edit the source
file and recompile.
.SH OPTIONS
.IP -h
display usage and help info
.SH EXAMPLES
.SH
.SH FILES
.SH
.SH SEE ALSO
.SH
.SH BUGS
.SH
.SH COPYING
.I Copyright\ 1995-2008\ Jim\ Jackson
.PP
The software described by this manual is covered by the GNU General
Public License, Version 2, June 1991, issued by :
.IP
Free Software Foundation, Inc.,
.br
675 Mass Ave,
.br
Cambridge, MA 02139, USA
.PP
Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.
.PP
Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.
.PP
Permission is granted to copy and distribute translations of this
manual into another language, under the above conditions for modified
versions, except that this permission notice may be included in
translation instead of in the original English.
.SH AUTHOR
.I Jim Jackson
.br
.sp
.I Email: jj@franjam.org.uk
.br
