#! /bin/sh
#
# Usage: dtmf singledigit(s)
#
# example: dtmf 0 1 1 3 6 6 6 6

if [ -x ../tones ] ; then
 t="../tones"
else
 t=tones
fi

t="$t sin :150"

while [ "$1" != "" ]; do
 case $1 in
 0)
  t="$t 941,1336 "
  ;;
 1)
  t="$t 697,1209 "
  ;;
 2)
  t="$t 697,1336 "
  ;;
 3)
  t="$t 697,1477 "
  ;;
 4)
  t="$t 770,1209 "
  ;;
 5)
  t="$t 770,1336 "
  ;;
 6)
  t="$t 770,1477 "
  ;;
 7)
  t="$t 852,1209 "
  ;;
 8)
  t="$t 852,1336 "
  ;;
 9)
  t="$t 852,1477 "
  ;;
 esac
 t="$t 0,0:70"
 shift
done

$t

